spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
#    url: jdbc:h2:mem:querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

    #    url: jdbc:mysql://192.168.0.40:3306/querydsl
    #    url: jdbc:mysql://localhost:3306/querydsl
    #    username: root
    #    password: apmsetup
    #    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mariadb://localhost:3307/querydsl
#    username: root
#    password: apmsetup
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace